### ISSUE TITLE
[BUG]v0.3.5 pd-disagg: UnboundLocalError: cannot access local variable 'local_cpu_backend' where it is not associated with a value

### ISSUE THREAD

**Issue by mgw2168-1** [LMCache/LMCache#1478]
**Label**
Please label your issue with "bug" and any other relevant labels so that it can easily be easily categorized under [LMCache Onboarding](https://github.com/LMCache/LMCache/issues/627)

**Describe the bug**

Prefiller can start normally, but decoder cannot.

**my configs:**
1.prefiller
```
local_cpu: True
max_local_cpu_size: 5
max_local_disk_size: 100
local_disk: "file://local_disk/"

enable_nixl: True
enable_xpyd: True
nixl_role: "sender"
nixl_proxy_host: "localhost"
nixl_proxy_port: 7500
nixl_buffer_size: 1073741824 # 1GB
nixl_buffer_device: "cuda"
nixl_backends: [UCX]
```

2.decoder
```
local_cpu: False
max_local_cpu_size: 0

enable_nixl: True
enable_xpyd: True
nixl_role: "receiver"
nixl_peer_host: "localhost"
nixl_peer_init_port: 7300
nixl_peer_alloc_port: 7400
nixl_buffer_size: 2147483648 # 2GB
nixl_buffer_device: "cuda"
nixl_backends: [UCX]

```

**commands:**
1.prefiller
```
export PYTHONHASHSEED=0
MODEL=/models/Qwen3-4B-FP8
prefill_config_file=/models/LMCache/examples/disagg_prefill/1p1d_experimental/configs/lmcache-prefiller-config.yaml
VLLM_LOGGING_LEVEL=DEBUG \
LMCACHE_LOG_LEVEL=DEBUG \
UCX_TLS=cuda_ipc,cuda_copy,tcp \
    LMCACHE_CONFIG_FILE=$prefill_config_file \
    LMCACHE_USE_EXPERIMENTAL=True \
    VLLM_ENABLE_V1_MULTIPROCESSING=1 \
    VLLM_WORKER_MULTIPROC_METHOD=spawn \
    CUDA_VISIBLE_DEVICES=0 \
    vllm serve $MODEL \
    --port 7100 \
    --no-enable-prefix-caching \
    --gpu-memory-utilization 0.8 \
    --kv-transfer-config \
    '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_producer","kv_connector_extra_config": {"discard_partial_chunks": false, "lmcache_rpc_port": "producer1"}}'

```

2.decoder
```
export PYTHONHASHSEED=0
MODEL=/models/Qwen3-4B-FP8
decode_config_file=/models/LMCache/examples/disagg_prefill/1p1d_experimental/configs/lmcache-decoder-config.yaml
VLLM_LOGGING_LEVEL=DEBUG \
LMCACHE_LOG_LEVEL=DEBUG \
UCX_TLS=cuda_ipc,cuda_copy,tcp \
    LMCACHE_CONFIG_FILE=$decode_config_file \
    LMCACHE_USE_EXPERIMENTAL=True \
    VLLM_ENABLE_V1_MULTIPROCESSING=1 \
    VLLM_WORKER_MULTIPROC_METHOD=spawn \
    CUDA_VISIBLE_DEVICES=1 \
    vllm serve $MODEL \
    --port 7200 \
    --no-enable-prefix-caching \
    --gpu-memory-utilization 0.7 \
    --kv-transfer-config \
    '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_consumer","kv_connector_extra_config": {"discard_partial_chunks": false, "lmcache_rpc_port": "consumer1", "skip_last_n_tokens": 1}}'

```

**Expected behavior**

```
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700] EngineCore failed to start.
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700] Traceback (most recent call last):
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     self.model_executor = executor_class(vllm_config)
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     self._init_executor()
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     self.collective_rpc("init_device")
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     return func(*args, **kwargs)
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     self.worker.init_device()  # type: ignore
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 192, in init_device
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     init_worker_distributed_environment(self.vllm_config, self.rank,
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 612, in init_worker_distributed_environment
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     ensure_kv_transfer_initialized(vllm_config)
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_transfer_state.py", line 63, in ensure_kv_transfer_initialized
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     _KV_CONNECTOR_AGENT = KVConnectorFactory.create_connector(
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_connector/factory.py", line 60, in create_connector
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     return connector_cls(config, role)
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_connector/v1/lmcache_connector.py", line 27, in __init__
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     self._lmcache_engine = LMCacheConnectorV1Impl(vllm_config, role, self)
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/lmcache/integration/vllm/vllm_v1_adapter.py", line 557, in __init__
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     self.lmcache_engine = _init_lmcache_engine(
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/lmcache/integration/vllm/vllm_v1_adapter.py", line 503, in _init_lmcache_engine
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     engine = LMCacheEngineBuilder.get_or_create(
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/cache_engine.py", line 1345, in get_or_create
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     engine = LMCacheEngine(
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]              ^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/cache_engine.py", line 125, in __init__
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     self.storage_manager = StorageManager(
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]                            ^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/storage_backend/storage_manager.py", line 66, in __init__
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     CreateStorageBackends(
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/storage_backend/__init__.py", line 207, in CreateStorageBackends
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     local_cpu_backend,
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700]     ^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) ERROR 09-01 02:01:11 [core.py:700] UnboundLocalError: cannot access local variable 'local_cpu_backend' where it is not associated with a value
(EngineCore_0 pid=2353) Process EngineCore_0:
(EngineCore_0 pid=2353) Traceback (most recent call last):
(EngineCore_0 pid=2353)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_0 pid=2353)     self.run()
(EngineCore_0 pid=2353)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore_0 pid=2353)     self._target(*self._args, **self._kwargs)
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 704, in run_engine_core
(EngineCore_0 pid=2353)     raise e
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
(EngineCore_0 pid=2353)     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_0 pid=2353)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
(EngineCore_0 pid=2353)     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
(EngineCore_0 pid=2353)     self.model_executor = executor_class(vllm_config)
(EngineCore_0 pid=2353)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_0 pid=2353)     self._init_executor()
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
(EngineCore_0 pid=2353)     self.collective_rpc("init_device")
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
(EngineCore_0 pid=2353)     answer = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_0 pid=2353)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
(EngineCore_0 pid=2353)     return func(*args, **kwargs)
(EngineCore_0 pid=2353)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
(EngineCore_0 pid=2353)     self.worker.init_device()  # type: ignore
(EngineCore_0 pid=2353)     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 192, in init_device
(EngineCore_0 pid=2353)     init_worker_distributed_environment(self.vllm_config, self.rank,
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 612, in init_worker_distributed_environment
(EngineCore_0 pid=2353)     ensure_kv_transfer_initialized(vllm_config)
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_transfer_state.py", line 63, in ensure_kv_transfer_initialized
(EngineCore_0 pid=2353)     _KV_CONNECTOR_AGENT = KVConnectorFactory.create_connector(
(EngineCore_0 pid=2353)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_connector/factory.py", line 60, in create_connector
(EngineCore_0 pid=2353)     return connector_cls(config, role)
(EngineCore_0 pid=2353)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/vllm/distributed/kv_transfer/kv_connector/v1/lmcache_connector.py", line 27, in __init__
(EngineCore_0 pid=2353)     self._lmcache_engine = LMCacheConnectorV1Impl(vllm_config, role, self)
(EngineCore_0 pid=2353)                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/lmcache/integration/vllm/vllm_v1_adapter.py", line 557, in __init__
(EngineCore_0 pid=2353)     self.lmcache_engine = _init_lmcache_engine(
(EngineCore_0 pid=2353)                           ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/lmcache/integration/vllm/vllm_v1_adapter.py", line 503, in _init_lmcache_engine
(EngineCore_0 pid=2353)     engine = LMCacheEngineBuilder.get_or_create(
(EngineCore_0 pid=2353)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/cache_engine.py", line 1345, in get_or_create
(EngineCore_0 pid=2353)     engine = LMCacheEngine(
(EngineCore_0 pid=2353)              ^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/cache_engine.py", line 125, in __init__
(EngineCore_0 pid=2353)     self.storage_manager = StorageManager(
(EngineCore_0 pid=2353)                            ^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/storage_backend/storage_manager.py", line 66, in __init__
(EngineCore_0 pid=2353)     CreateStorageBackends(
(EngineCore_0 pid=2353)   File "/opt/venv/lib/python3.12/site-packages/lmcache/v1/storage_backend/__init__.py", line 207, in CreateStorageBackends
(EngineCore_0 pid=2353)     local_cpu_backend,
(EngineCore_0 pid=2353)     ^^^^^^^^^^^^^^^^^
(EngineCore_0 pid=2353) UnboundLocalError: cannot access local variable 'local_cpu_backend' where it is not associated with a value
(APIServer pid=2072) DEBUG 09-01 02:01:20 [utils.py:750] Waiting for 1 local, 0 remote core engine proc(s) to start.

```

**Comment by jaydsolanki** [comment]
I am getting the same error when upgrading from 0.3.3 to 0.3.5. 
I tried doing the following to check if it would work:
In the storage_backend directory update the `__init__.py` file to explictly define `local_cpu_backend`
For example
`vi /usr/local/lib/python3.12/dist-packages/lmcache/v1/storage_backend/__init__.py`
Goto  line 143
change `pass` to `local_cpu_backend = None`

```
    if config.enable_nixl and not config.local_cpu:
-        pass
+        local_cpu_backend = None
    else:
        local_cpu_backend = LocalCPUBackend(
            config,
            memory_allocator,
            lookup_server,
            lmcache_worker,
        )
        backend_name = str(local_cpu_backend)
        storage_backends[backend_name] = local_cpu_backend

```

But that raised another error

```
assert isinstance(allocator_backend, AllocatorBackendInterface)
File "/usr/local/lib/python3.12/dist-packages/lmcache/v1/storage_backend/storage_manager.py", line 100, in _get_allocator_backend
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AssertionError

```

I find that the connector is of type: `allocator_backend: <class 'lmcache.v1.storage_backend.nixl_backend.NixlBackend'>`


This is the config i am using:

```
Creating LMCacheEngine with config: {'chunk_size': 256, 'local_cpu': False, 'max_local_cpu_size': 0.0, 'local_disk': None, 'max_local_disk_size': 0.0, 'remote_url': None, 'remote_serde': None, 'use_layerwise': False, 'save_decode_cache': False, 'pre_caching_hash_algorithm': 'builtin', 'enable_blending': False, 'blend_recompute_ratio': 0.15, 'blend_min_tokens': 256, 'blend_special_str': ' # # ', 'enable_p2p': False, 'lookup_url': None, 'distributed_url': None, 'error_handling': False, 'enable_controller': False, 'lmcache_instance_id': 'lmcache_default_instance', 'controller_url': None, 'lmcache_worker_port': None, 'lmcache_worker_heartbeat_delay_time': 10, 'lmcache_worker_heartbeat_time': None, 'enable_nixl': True, 'nixl_role': 'receiver', 'nixl_receiver_host': '172.31.57.69', 'nixl_receiver_port': 55555, 'nixl_buffer_size': 1073741824, 'nixl_buffer_device': 'cuda', 'nixl_enable_gc': True, 'nixl_backends': None, 'enable_xpyd': False, 'nixl_peer_host': None, 'nixl_peer_init_port': None, 'nixl_peer_alloc_port': None, 'nixl_proxy_host': None, 'nixl_proxy_port': None, 'weka_path': None, 'gds_path': None, 'cufile_buffer_size': None, 'audit_actual_remote_url': None, 'internal_api_server_host': '0.0.0.0', 'extra_config': None, 'save_unfull_chunk': True, 'blocking_timeout_secs': 10, 'external_lookup_client': None, 'py_enable_gc': True, 'cache_policy': 'LRU', 'numa_mode': None, 'internal_api_server_enabled': False, 'internal_api_server_port_start': 6999, 'internal_api_server_include_index_list': None, 'internal_api_server_socket_path_prefix': None, 'plugin_locations': None, 'external_backends': None} (cache_engine.py:93:lmcache.v1.cache_engine)


```

**Comment by ApostaC** [comment]
@Shaoting-Feng Can you take a look at this issue?

**Comment by Shaoting-Feng** [comment]
@mgw2168-1 @jaydsolanki This error is fixed in https://github.com/LMCache/LMCache/pull/1494. Please check out our latest codes. Thanks!

**Comment by jaydsolanki** [comment]
The second issue in my previous comment is still not fixed. I took the latest code and I am still getting 

```
File "/usr/local/lib/python3.12/dist-packages/lmcache/v1/storage_backend/storage_manager.py", line 153, in _get_allocator_backend
 AssertionError
     assert isinstance(allocator_backend, AllocatorBackendInterface)

```

**Comment by Shaoting-Feng** [comment]
> The second issue in my previous comment is still not fixed. I took the latest code and I am still getting
> 
> ```
> File "/usr/local/lib/python3.12/dist-packages/lmcache/v1/storage_backend/storage_manager.py", line 153, in _get_allocator_backend
>  AssertionError
>      assert isinstance(allocator_backend, AllocatorBackendInterface)
> ```

What is your LMCache config for prefiller and decoder?

**Comment by jaydsolanki** [comment]
Hi @Shaoting-Feng, as this particular issue is fixed in latest commits (https://github.com/LMCache/LMCache/pull/1494),  I have created another ticket with better description and config here: https://github.com/LMCache/LMCache/issues/1551

**Comment by cdc542559455** [comment]
The issue was addressed and resolved the problem.
